// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYRoox_PrOR3sMw0EajF6KKCPSByVWw44',
    appId: '1:507784702917:web:ea0a07db4395ce594ff9ac',
    messagingSenderId: '507784702917',
    projectId: 'herewego-9efda',
    authDomain: 'herewego-9efda.firebaseapp.com',
    storageBucket: 'herewego-9efda.appspot.com',
    measurementId: 'G-NCFTWR6XVK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDc5fSUKGpmlwym7oNMooPUdixcoma9G-M',
    appId: '1:507784702917:android:e9b0f707c56881df4ff9ac',
    messagingSenderId: '507784702917',
    projectId: 'herewego-9efda',
    storageBucket: 'herewego-9efda.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGS6oo4jwN_8mLKrTeXrS1V8xMNU3pghI',
    appId: '1:507784702917:ios:6ccc9b5811ba39da4ff9ac',
    messagingSenderId: '507784702917',
    projectId: 'herewego-9efda',
    storageBucket: 'herewego-9efda.appspot.com',
    iosClientId: '507784702917-vc0u5ur9nbrurl5eqivvbj3mhtblipmr.apps.googleusercontent.com',
    iosBundleId: 'com.example.herewegoo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGS6oo4jwN_8mLKrTeXrS1V8xMNU3pghI',
    appId: '1:507784702917:ios:fd5631cc2664f8b94ff9ac',
    messagingSenderId: '507784702917',
    projectId: 'herewego-9efda',
    storageBucket: 'herewego-9efda.appspot.com',
    iosClientId: '507784702917-bu1c36ub3b66ud7cetc6niojrp0c7ik3.apps.googleusercontent.com',
    iosBundleId: 'com.example.herewegoo.RunnerTests',
  );
}
